### ISSUE TITLE
Doesn't work on 10.14 macOS

### ISSUE THREAD

**Issue by nikivdev** [codebasesaga/gitx#1]
Get this message:

![2018-09-26 at 19 09](https://user-images.githubusercontent.com/6391776/46096524-b4246b00-c1bf-11e8-8493-2b625e23d0cc.png)

Here are the details of the crash:

Process:               GitX [70530]
Path:                  /private/var/folders/*/GitX.app/Contents/MacOS/GitX
Identifier:            com.codebasesaga.macOS.GitX
Version:               0.15.2478 dev (0.15.2478)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           GitX [70530]
User ID:               501

Date/Time:             2018-09-26 19:09:30.943 +0200
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Bridge OS Version:     3.0 (16P375)
Anonymous UUID:        208B671E-A745-3C26-0B57-218A5F0805C7

Sleep/Wake UUID:       B9AA5B29-4785-4EA4-9188-2429B72B6E3D

Time Awake Since Boot: 55000 seconds
Time Since Wake:       3300 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /private/var/folders/5l/5s7qw5ld1xxglm0094_hyh_c0000gn/T/AppTranslocation/EDD41CE8-5EDD-4762-A4BB-E298997A8E29/d/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit
  Reason: image not found

Binary Images:
       0x10d0f8000 -        0x10d2eafff +com.codebasesaga.macOS.GitX (0.15.2478 dev - 0.15.2478) <60F6E6FF-9B1F-3A36-AC9C-59265479DE4A> /var/folders/*/GitX.app/Contents/MacOS/GitX
       0x10d388000 -        0x10d5fcff7 +org.libgit2.ObjectiveGit (1.0 - ???) <45494408-FC18-3805-91FD-328AB53975DC> /var/folders/*/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit
       0x10d6f7000 -        0x10d790feb +libclang_rt.asan_osx_dynamic.dylib (1000.10.40.1) <4491E836-A8FB-3517-8839-5D2577C1AED8> /var/folders/*/GitX.app/Contents/Frameworks/libclang_rt.asan_osx_dynamic.dylib
       0x11ba26000 -        0x11baa46a7  dyld (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> /usr/lib/dyld
    0x7fff3bce7000 -     0x7fff3cb06ff3  com.apple.AppKit (6.9 - 1671) <E1B2CAF1-9231-3B3D-BD9E-B770FE87F407> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3df4e000 -     0x7fff3df4efff  com.apple.Cocoa (6.11 - 23) <A520D2A3-032B-3C06-81E1-EFDD97C47ACE> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff3e770000 -     0x7fff3ebbffff  com.apple.CoreFoundation (6.9 - 1555.10) <4A4C87BC-4C8E-392A-ABEE-824D4074C485> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3ebc1000 -     0x7fff3f24efff  com.apple.CoreGraphics (2.0 - 1245.8.4.8) <FFFFEAF0-14DD-38A3-BD68-AA9AB2C672C1> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff3fa2c000 -     0x7fff3fa2cfff  com.apple.CoreServices (933 - 933) <B79C910E-93B9-3686-8E72-E0B63083AAE5> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff40aef000 -     0x7fff40ebdfff  com.apple.Foundation (6.9 - 1555.10) <0CCAF9AF-F7AF-3174-98D4-6C188B1079CC> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff49729000 -     0x7fff49729fff  com.apple.quartzframework (1.5 - 23) <103A742C-50F3-3A4A-B787-FDD35F36B6F1> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff4972a000 -     0x7fff49980fff  com.apple.QuartzCore (1.11 - 693.16.4.2) <2C9E3279-3F97-3440-B937-E5FE888232E2> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff4a1b5000 -     0x7fff4a1cdfff  com.apple.ScriptingBridge (1.4 - 77) <3502C869-965C-3D65-AC25-D18636CBA127> /System/Library/Frameworks/ScriptingBridge.framework/Versions/A/ScriptingBridge
    0x7fff4a1ce000 -     0x7fff4a4f4fff  com.apple.security (7.0 - 58286.200.222) <AEB638D9-BFE9-319E-A70B-557ACF41117A> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff4a977000 -     0x7fff4a9e7ff3  com.apple.SystemConfiguration (1.17 - 1.17) <EED5BC9B-CE8D-343C-BCDC-04A79F704828> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff4d2b8000 -     0x7fff4d7b5fff  com.apple.WebKit (14606 - 14606.1.36.1.9) <5E4AF277-D207-3647-9D5C-A6F1543A2D4D> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff68cb5000 -     0x7fff68cb6ffb  libSystem.B.dylib (1252.200.5) <D5133811-9D66-3DEB-9521-0A67347C9A54> /usr/lib/libSystem.B.dylib
    0x7fff68f10000 -     0x7fff68f67ff7  libc++.1.dylib (400.9.4) <D4AB366F-48A9-3C7D-91BD-41198F69DD57> /usr/lib/libc++.1.dylib
    0x7fff6a75c000 -     0x7fff6aee2fe7  libobjc.A.dylib (750) <2E868147-8818-359E-8CD7-A8B80665928F> /usr/lib/libobjc.A.dylib

Model: MacBookPro15,1, BootROM 220.200.252.0.0 (iBridge: 16.16.375.0.0,0), 6 processors, Intel Core i7, 2.6 GHz, 32 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, Built-In
Graphics: kHW_AMDRadeonPro560XItem, Radeon Pro 560X, PCIe
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2400 MHz, Micron, 16ATS2G64HZ-2G6B1 16ATS2G64HZ-2G6B1
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2400 MHz, Micron, 16ATS2G64HZ-2G6B1 16ATS2G64HZ-2G6B1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Jul 24 2018 08:46:21 version 9.130.86.2.32.6.17 FWID 01-a7e14b32
Bluetooth: Version 6.0.8f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: iBridge Bus
USB Device: iBridge DFR brightness
USB Device: iBridge Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: iBridge ALS
USB Device: iBridge FaceTime HD Camera (Built-in)
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 30.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 30.2

**Comment by nikivdev** [comment]
Oh I just read that `openssl` needs to be installed to `/usr/local`. That's a shame since I use [nix](https://nixos.org/nix/).

Any way to specify for gitfx the location of openssl or it just have to be in the PATH?

Thank you.

**Comment by mxcl** [comment]
yes, sorry about this. I spent a while trying to fix it, but it's basically an upstream issue. The libgit2-objc people decided to make their library depend on Homebrew with no workaround for release-builds at this time.

Will leave open in case anyone has any solutions.

**Comment by nikivdev** [comment]
How can you depend on Homebrew? It's just a package manager.

**Comment by manmal** [comment]
I have a slightly different problem, also on Mojave. I updated brew, uninstalled all openssl versions, and reinstalled openssl. Alas, `libcrypto.1.0.0.dylib` cannot be loaded, apparently because it's not signed - a brew problem on Mojave perhaps?

The relevant part of the crash log is here:

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit
  Reason: no suitable image found.  Did find:
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: code signature in (/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: stat() failed with errno=1
	/usr/local/Cellar/openssl/1.0.2p/lib/libcrypto.1.0.0.dylib: code signature in (/usr/local/Cellar/openssl/1.0.2p/lib/libcrypto.1.0.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

When googling for `mapped file has no cdhash` some similar problems turn up, but I've found nothing worthwhile so far.

**Comment by mxcl** [comment]
This is the error you get when openssl is not installed, are you 100% sure `/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib` exists?

What does `ls -la /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib` say?

**Comment by mxcl** [comment]
> How can you depend on Homebrew? It's just a package manager.

I don’t, `ObjectiveGit.framework` does; it depends on openssl being installed to `/usr/local/opt`.

**Comment by nikivdev** [comment]
https://github.com/openssl/openssl

This one right?

Will send a PR then. Or perhaps a symlink might work.

**Comment by manmal** [comment]
> This is the error you get when openssl is not installed, are you 100% sure `/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib` exists?
> 
> What does `ls -la /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib` say?

Yes, it's installed. `ls -la` says:
```
-rw-r--r--  1 manuelmaly  staff  1866588 Sep 26 20:00 /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
```

**Comment by mxcl** [comment]
I've tested it on multiple machines and afaik it doesn't need to be signed since it is a debug build. Possibly you just need to open the app once holding option so that you can stop Gatekeeper from being a pain.

**Comment by bfolberth** [comment]
> > This is the error you get when openssl is not installed, are you 100% sure `/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib` exists?
> > What does `ls -la /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib` say?
> 
> Yes, it's installed. `ls -la` says:
> 
> ```
> -rw-r--r--  1 manuelmaly  staff  1866588 Sep 26 20:00 /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
> ```

+1. Exact same issue here.

**Comment by manmal** [comment]
> I've tested it on multiple machines and afaik it doesn't need to be signed since it is a debug build. Possibly you just need to open the app once holding option so that you can stop Gatekeeper from being a pain.

This was necessary at first run, yes, or the OS won't let me start the app at all. I've googled some more—it seems Homebrew does not generally codesign binaries.

Very recklessly, I copy-pasted this dylib Binary: https://github.com/zoom/zoom-sdk-macos/raw/master/ZoomSDK/libcrypto.1.0.0.dylib

Which lead to a different, somewhat expected error:
```
/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: code signature in (/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
```

I suspect that I either have to codesign libcrypto with my own dev account (have to figure out how), or switch off Library Validation: https://github.com/mologie/macos-disable-library-validation

Maybe I'll try this on the weekend.

**Comment by mxcl** [comment]
My openssl is the binary Homebrew delivers.

**Comment by victorg1991** [comment]
the same for me :(

I do have openssl too
`-r--r--r--  1 victorg  admin  1986176 Jun  7 11:28 /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib`

**Comment by mxcl** [comment]
K well I guess I'll put some time into packaging the openssl from brew into the `.app`, sorry for the hassle everybody…

**Comment by mxcl** [comment]
I’ve opened a ticket on ObjcGit to try and resolve this: https://github.com/libgit2/objective-git/issues/667

**Comment by mxcl** [comment]
I have uploaded a new build at the release url (marked `-r2`), please try it out, I think it is good now.

**Comment by mxcl** [comment]
Please reopen if not fixed.

**Comment by victorg1991** [comment]
Thanks a lot, @mxcl for your effort. Works like a charm :)
